#!/usr/bin/env python3
"""Local backend for the `polyrith'` tactic: a Nullstellensatz certificate from Singular.

Mathlib's `polyrith` proved polynomial goals by asking a public SageMath server for the
coefficients of a linear combination, then emitting a `linear_combination` call for Lean to
check. That server was shut down in 2025 and the tactic was removed, with a note that it
"could be restored if someone wanted to provide an alternative backend". This is that
backend, run locally against Singular through `passagemath-singular`.

The query arrives on stdin exactly as the tactic used to send it to the service, and the
reply goes to stdout in the same JSON envelope the service returned, so everything on the
Lean side is unchanged. `scripts/polyrith_helper.py` is Mathlib's helper, byte for byte.

**The query is Sage source, not Python, and must be preparsed.** `Poly.format` emits `^` for
exponentiation, which Sage's REPL rewrites to `**`; run as plain Python it means exclusive-or,
and Sage raises rather than computing something wrong. Preparsing also wraps numeric literals
in `Integer(...)`, so `1/3` stays an exact rational instead of becoming a float and dragging
the polynomial ring into `Real Double Field`. That second effect turns out not to change any
answer in testing — Sage recovers the simplest rational from a float, even for a denominator
like 1000000007 — but it is a detour worth not taking when preparsing is free.

Nothing here is trusted. The certificate is a *suggestion*: Lean elaborates the resulting
`linear_combination` and checks it, so a wrong answer from Singular cannot produce a theorem,
only a tactic failure. That is why this may run against an unpinned Singular when an unpinned
lemma index would be unacceptable.
"""

from __future__ import annotations

import io
import json
import sys
from contextlib import redirect_stdout


def _fail(name: str, value: str) -> int:
    """Report as the SageCell service did, so the Lean-side parser needs no special case."""
    print(json.dumps({"success": False, "execute_reply": {"ename": name, "evalue": value}}))
    return 1


def main() -> int:
    query = sys.stdin.read()
    if not query.strip():
        return _fail("EmptyQuery", "no query on stdin")

    try:
        # Only the Singular-backed polynomial machinery is needed, not all of Sage.
        from sage.all__sagemath_singular import QQ, PolynomialRing
        from sage.repl.preparse import preparse
        from sage.rings.integer import Integer
        from sage.rings.real_mpfr import RealNumber
    except ImportError as exc:
        return _fail(
            "MissingBackend",
            f"{exc}. Install the backend with "
            "`pip install passagemath-singular passagemath-repl`, and point "
            "NULLIUS_PYTHON at that interpreter.",
        )

    # `Integer` and `RealNumber` are the names the preparser generates for numeric literals.
    env = {
        "QQ": QQ, "PolynomialRing": PolynomialRing,
        "Integer": Integer, "RealNumber": RealNumber, "json": json,
    }
    buf = io.StringIO()
    try:
        with redirect_stdout(buf):
            exec(preparse(query), env)  # noqa: S102 - generated by the tactic, not a user
    except Exception as exc:  # noqa: BLE001 - reported to Lean rather than swallowed
        return _fail(type(exc).__name__, str(exc))

    print(json.dumps({"success": True, "stdout": buf.getvalue()}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
